# Generated by Django 3.2.22 on 2024-08-18 03:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_remove_contact_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_submitted',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
